[package]
name = "quetta"
version = "0.0.1"
compiler = "0.11.1"
repository = "https://github.com/FlorentCLMichel/quetta"
entrypoint = "quetta.typ"
authors = [
  "Florent Michel <https://github.com/FlorentCLMichel>",
]
categories = [ "languages" ]
license = "MIT"
description = "Easily write in Tengwar with Typst."
keywords = [ "typography", "tengwar", "fantasy" ]
exclude = [ "manual.pdf", "manual.typ" ]
